[package]
name = "gpsd_proto"
version = "0.1.1"

license = "Apache-2.0"
repository = "https://github.com/bwolf/gpsd_proto"
documentation = "https://docs.rs/gpsd_proto/"
readme = "README.md"
authors = ["Marcus Geiger"]

description = "The gpsd_proto module contains types and functions to connect to gpsd to get GPS coordinates and satellite information."

keywords = ["gps"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
