[package]
name = "gpsd_example"
version = "0.1.0"
authors = ["Marcus Geiger <git010@teufelsgraben.xyz>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
itertools = "0.7.8"
gpsd_proto = { path = ".." }
